export interface LocationData {
  slug: string;
  name: string;
  type: 'pillar' | 'secondary';
  keyword: string;
  volume: number;
  tagline: string;
  intro: string;
  street: string;
  city: string;
  postalCode: string;
  latitude: string;
  longitude: string;
  rating: string;
  reviews: string;
  attractions: string[];
  routes: { from: string; to: string; time: string }[];
  deliveryNote: string;
  neighbors: string[]; // slugs
}

export const LOCATIONS: LocationData[] = [
  // ─── Pillar Pages ───────────────────────────────────────────────────────────
  {
    slug: 'lapu-lapu',
    name: 'Lapu-Lapu City',
    type: 'pillar',
    keyword: 'rent scooter lapu-lapu',
    volume: 350,
    tagline: 'Free Delivery Across Lapu-Lapu',
    intro: 'Lapu-Lapu City is home to Mactan Airport and some of Cebu\'s most beautiful beach resorts. Our main hub is based here — which means the fastest delivery times and the largest scooter selection.',
    street: 'Lapu-Lapu City',
    city: 'Lapu-Lapu City',
    postalCode: '6015',
    latitude: '10.3077',
    longitude: '123.9790',
    rating: '4.9',
    reviews: '143',
    attractions: ['Mactan-Cebu International Airport', 'Mactan Shrine', 'Shangri-La Mactan Resort', 'Hopping Island', 'Maribago Beach', 'Mactan Newtown'],
    routes: [
      { from: 'Lapu-Lapu Center', to: 'Mactan Airport', time: '10 min' },
      { from: 'Lapu-Lapu Center', to: 'Cebu City', time: '35 min' },
      { from: 'Lapu-Lapu Center', to: 'Shangri-La Resort', time: '15 min' },
    ],
    deliveryNote: 'Our main base is in Lapu-Lapu City — delivery takes 20–35 minutes anywhere in the city.',
    neighbors: ['mactan-airport', 'mactan', 'cordova'],
  },
  {
    slug: 'mactan-airport',
    name: 'Mactan Airport',
    type: 'pillar',
    keyword: 'rent scooter mactan airport',
    volume: 420,
    tagline: 'Free Airport Pickup · Meet You at Arrivals',
    intro: 'Just landed? Skip the taxi queue. KJM Motors offers free scooter pickup at Mactan-Cebu International Airport — we meet you at arrivals within 30 minutes of your booking. No waiting, no hidden fees.',
    street: 'Mactan-Cebu International Airport',
    city: 'Lapu-Lapu City',
    postalCode: '6015',
    latitude: '10.3077',
    longitude: '123.9790',
    rating: '4.9',
    reviews: '87',
    attractions: ['Terminal 1 Arrivals', 'Terminal 2 Arrivals', 'Airport Mall', 'Mactan Shrine (15 min)', 'Beach Resorts (15–25 min)'],
    routes: [
      { from: 'Airport', to: 'Lapu-Lapu City Center', time: '10 min' },
      { from: 'Airport', to: 'Cebu City', time: '30 min' },
      { from: 'Airport', to: 'Maribago Beach', time: '15 min' },
    ],
    deliveryNote: 'We meet you inside the arrivals hall. Just book before landing — average wait is under 30 minutes.',
    neighbors: ['lapu-lapu', 'mactan', 'cebu-city'],
  },
  {
    slug: 'mactan',
    name: 'Mactan Island',
    type: 'pillar',
    keyword: 'scooter rental mactan',
    volume: 280,
    tagline: 'Explore Every Beach on Mactan Island',
    intro: 'Mactan Island is Cebu\'s tourist heartland — home to beach resorts, island-hopping operators, and the international airport. A scooter is the easiest way to hop between beaches and explore the island independently.',
    street: 'Mactan Island',
    city: 'Lapu-Lapu City',
    postalCode: '6015',
    latitude: '10.2941',
    longitude: '123.9601',
    rating: '4.8',
    reviews: '112',
    attractions: ['Mactan Shrine', 'Shangri-La Resort', 'Crimson Resort', 'Mactan Newtown', 'Hopping Island Operators', 'Seafood Market'],
    routes: [
      { from: 'Mactan', to: 'Cebu City via Mandaue Bridge', time: '30 min' },
      { from: 'Mactan', to: 'Mactan Airport', time: '10 min' },
      { from: 'Mactan', to: 'Olango Island Ferry', time: '20 min' },
    ],
    deliveryNote: 'We deliver anywhere on Mactan Island in 20–40 minutes depending on your exact location.',
    neighbors: ['lapu-lapu', 'mactan-airport', 'cordova'],
  },
  {
    slug: 'cebu-city',
    name: 'Cebu City',
    type: 'pillar',
    keyword: 'rent scooter cebu city',
    volume: 600,
    tagline: 'Free Delivery to Your Hotel or Office',
    intro: 'Cebu City is the beating heart of the Visayas — a city of heritage churches, modern malls, and buzzing business districts like IT Park and Ayala. Traffic can be brutal; a scooter gives you back your time and saves you hundreds of pesos a day in Grab fares.',
    street: 'Cebu City',
    city: 'Cebu City',
    postalCode: '6000',
    latitude: '10.3157',
    longitude: '123.8854',
    rating: '4.8',
    reviews: '156',
    attractions: ['IT Park', 'Ayala Center Cebu', 'SM Seaside City', 'Basilica del Santo Niño', 'Fort San Pedro', 'Carbon Market', 'South Road Properties'],
    routes: [
      { from: 'Cebu City', to: 'IT Park', time: '10 min' },
      { from: 'Cebu City', to: 'Mactan Airport', time: '35 min' },
      { from: 'Cebu City', to: 'Tops Lookout (Busay)', time: '25 min' },
    ],
    deliveryNote: 'We deliver to any hotel, condo, or address in Cebu City in 30–60 minutes.',
    neighbors: ['it-park', 'mabolo', 'mandaue', 'talisay'],
  },
  {
    slug: 'it-park',
    name: 'IT Park',
    type: 'pillar',
    keyword: 'motorcycle rental it park cebu',
    volume: 320,
    tagline: 'Daily & Monthly Rentals for IT Professionals',
    intro: 'IT Park Cebu is the city\'s top BPO and tech hub. If you work here or stay nearby, a monthly scooter rental is cheaper than three weeks of Grab rides — and you can park right at your building.',
    street: 'Cebu IT Park, Lahug',
    city: 'Cebu City',
    postalCode: '6000',
    latitude: '10.3270',
    longitude: '123.9055',
    rating: '4.8',
    reviews: '94',
    attractions: ['IT Park BPO Buildings', 'The Walk IT Park', 'Ayala Center Cebu (5 min)', 'JY Square Mall', 'Lahug Market'],
    routes: [
      { from: 'IT Park', to: 'Ayala Center', time: '5 min' },
      { from: 'IT Park', to: 'SM City Cebu', time: '12 min' },
      { from: 'IT Park', to: 'Mactan Airport', time: '30 min' },
    ],
    deliveryNote: 'We deliver directly to IT Park buildings and nearby Lahug addresses. Average time: 35 minutes.',
    neighbors: ['cebu-city', 'banilad', 'mabolo'],
  },
  {
    slug: 'mandaue',
    name: 'Mandaue City',
    type: 'pillar',
    keyword: 'rent scooter mandaue',
    volume: 250,
    tagline: 'Free Delivery Across Mandaue City',
    intro: 'Mandaue City connects Cebu City to Lapu-Lapu via the Marcelo Fernan Bridge. With its growing commercial zones and easy highway access, Mandaue is a smart base for exploring both cities.',
    street: 'Mandaue City',
    city: 'Mandaue City',
    postalCode: '6014',
    latitude: '10.3494',
    longitude: '123.9321',
    rating: '4.7',
    reviews: '78',
    attractions: ['SM City Cebu (border)', 'Gaisano Grand Mall', 'Mandaue Commercial Zone', 'Marcelo Fernan Bridge', 'North Reclamation Area'],
    routes: [
      { from: 'Mandaue', to: 'Cebu City', time: '20 min' },
      { from: 'Mandaue', to: 'Lapu-Lapu via Bridge', time: '25 min' },
      { from: 'Mandaue', to: 'Consolacion', time: '20 min' },
    ],
    deliveryNote: 'Free delivery to all Mandaue City addresses in 25–45 minutes.',
    neighbors: ['cebu-city', 'consolacion', 'lapu-lapu'],
  },

  // ─── Secondary Pages ─────────────────────────────────────────────────────────
  {
    slug: 'mabolo',
    name: 'Mabolo',
    type: 'secondary',
    keyword: 'rent scooter mabolo cebu',
    volume: 90,
    tagline: 'Free Delivery to Mabolo',
    intro: 'Mabolo is a central Cebu City neighborhood with easy access to IT Park, Ayala Center, and the main business districts. KJM Motors delivers free to any Mabolo address.',
    street: 'Mabolo, Cebu City',
    city: 'Cebu City',
    postalCode: '6000',
    latitude: '10.3220',
    longitude: '123.9100',
    rating: '4.8',
    reviews: '45',
    attractions: ['Robinsons Galleria', 'Mabolo Church', 'IT Park (10 min)', 'Ayala Center (8 min)'],
    routes: [
      { from: 'Mabolo', to: 'IT Park', time: '10 min' },
      { from: 'Mabolo', to: 'Ayala Center', time: '8 min' },
    ],
    deliveryNote: 'We deliver to any Mabolo address in 35–50 minutes.',
    neighbors: ['it-park', 'banilad', 'cebu-city'],
  },
  {
    slug: 'banilad',
    name: 'Banilad',
    type: 'secondary',
    keyword: 'rent scooter banilad cebu',
    volume: 110,
    tagline: 'Free Delivery to Banilad',
    intro: 'Banilad is one of Cebu\'s most accessible uptown neighborhoods, close to malls, schools, and business centers. Ideal for students and professionals looking for daily or monthly scooter rentals.',
    street: 'Banilad, Cebu City',
    city: 'Cebu City',
    postalCode: '6000',
    latitude: '10.3390',
    longitude: '123.9050',
    rating: '4.8',
    reviews: '52',
    attractions: ['Banilad Town Center', 'Gaisano Country Mall', 'University of San Carlos Talamban', 'IT Park (10 min)'],
    routes: [
      { from: 'Banilad', to: 'IT Park', time: '10 min' },
      { from: 'Banilad', to: 'Ayala Center', time: '8 min' },
    ],
    deliveryNote: 'Free delivery to all Banilad addresses in 40–55 minutes.',
    neighbors: ['it-park', 'mabolo', 'talamban'],
  },
  {
    slug: 'talamban',
    name: 'Talamban',
    type: 'secondary',
    keyword: 'rent scooter talamban cebu',
    volume: 80,
    tagline: 'Free Delivery to Talamban',
    intro: 'Talamban is a fast-growing residential and university area north of Cebu City. A scooter is the most efficient way to commute between campus and the city.',
    street: 'Talamban, Cebu City',
    city: 'Cebu City',
    postalCode: '6000',
    latitude: '10.3540',
    longitude: '123.9100',
    rating: '4.7',
    reviews: '38',
    attractions: ['University of San Carlos Talamban', 'Banilad Town Center (nearby)', 'Cebu North Road'],
    routes: [
      { from: 'Talamban', to: 'Banilad', time: '12 min' },
      { from: 'Talamban', to: 'Mandaue', time: '20 min' },
    ],
    deliveryNote: 'Free delivery to Talamban in 45–60 minutes.',
    neighbors: ['banilad', 'mandaue', 'consolacion'],
  },
  {
    slug: 'talisay',
    name: 'Talisay City',
    type: 'secondary',
    keyword: 'rent scooter talisay cebu',
    volume: 120,
    tagline: 'Free Delivery to Talisay City',
    intro: 'Talisay City sits south of Cebu City along the coast. It\'s the perfect base for exploring south Cebu\'s beaches — Moalboal, Kawasan Falls, and Oslob are all within reach.',
    street: 'Talisay City',
    city: 'Talisay City',
    postalCode: '6045',
    latitude: '10.2448',
    longitude: '123.8493',
    rating: '4.7',
    reviews: '61',
    attractions: ['Cebu South Road', 'Talisay Beach', 'SM Seaside City (15 min)', 'Naga City (nearby)'],
    routes: [
      { from: 'Talisay', to: 'SM Seaside Cebu', time: '15 min' },
      { from: 'Talisay', to: 'Moalboal', time: '90 min' },
    ],
    deliveryNote: 'Free delivery to Talisay City in 45–70 minutes.',
    neighbors: ['cebu-city', 'minglanilla'],
  },
  {
    slug: 'cordova',
    name: 'Cordova',
    type: 'secondary',
    keyword: 'rent scooter cordova cebu',
    volume: 95,
    tagline: 'Free Delivery to Cordova',
    intro: 'Cordova is a quiet municipality across from Mactan Island, known for its peaceful beaches and the Cordova Reef Village resort. A scooter makes island-hopping easy.',
    street: 'Cordova, Cebu',
    city: 'Cordova',
    postalCode: '6017',
    latitude: '10.2580',
    longitude: '123.9590',
    rating: '4.8',
    reviews: '34',
    attractions: ['Cordova Reef Village', 'Cordova Municipal Beach', 'Olango Island (ferry nearby)', 'Mactan Island (bridge)'],
    routes: [
      { from: 'Cordova', to: 'Lapu-Lapu', time: '20 min' },
      { from: 'Cordova', to: 'Olango Island Ferry', time: '15 min' },
    ],
    deliveryNote: 'Free delivery to Cordova in 40–60 minutes.',
    neighbors: ['lapu-lapu', 'mactan'],
  },
  {
    slug: 'consolacion',
    name: 'Consolacion',
    type: 'secondary',
    keyword: 'rent scooter consolacion cebu',
    volume: 70,
    tagline: 'Free Delivery to Consolacion',
    intro: 'Consolacion is a growing town north of Mandaue City with direct access to the national highway. A scooter is ideal for commuting to Cebu City or exploring the north Cebu coast.',
    street: 'Consolacion, Cebu',
    city: 'Consolacion',
    postalCode: '6001',
    latitude: '10.3748',
    longitude: '123.9583',
    rating: '4.7',
    reviews: '28',
    attractions: ['Consolacion Shrine', 'North Cebu Highway', 'Mandaue City (20 min)', 'Liloan (10 min)'],
    routes: [
      { from: 'Consolacion', to: 'Mandaue City', time: '20 min' },
      { from: 'Consolacion', to: 'Liloan', time: '10 min' },
    ],
    deliveryNote: 'Free delivery to Consolacion in 50–70 minutes.',
    neighbors: ['mandaue', 'liloan', 'talamban'],
  },
  {
    slug: 'liloan',
    name: 'Liloan',
    type: 'secondary',
    keyword: 'rent scooter liloan cebu',
    volume: 60,
    tagline: 'Free Delivery to Liloan',
    intro: 'Liloan is a scenic coastal municipality north of Consolacion. Ideal for those exploring the quieter north Cebu coast or commuting to Mandaue.',
    street: 'Liloan, Cebu',
    city: 'Liloan',
    postalCode: '6002',
    latitude: '10.3960',
    longitude: '123.9983',
    rating: '4.7',
    reviews: '22',
    attractions: ['Liloan Church', 'North Cebu Beaches', 'Consolacion (10 min)', 'Danao City (20 min)'],
    routes: [
      { from: 'Liloan', to: 'Consolacion', time: '10 min' },
      { from: 'Liloan', to: 'Mandaue', time: '25 min' },
    ],
    deliveryNote: 'Free delivery to Liloan in 55–75 minutes.',
    neighbors: ['consolacion', 'danao'],
  },
  {
    slug: 'busay',
    name: 'Busay',
    type: 'secondary',
    keyword: 'rent scooter busay cebu',
    volume: 75,
    tagline: 'Free Delivery to Busay · Ride to the Mountains',
    intro: 'Busay sits high in the hills above Cebu City, home to Tops Lookout — one of the best viewpoints on the island. A scooter is the perfect way to make the scenic uphill ride.',
    street: 'Busay, Cebu City',
    city: 'Cebu City',
    postalCode: '6000',
    latitude: '10.3290',
    longitude: '123.8710',
    rating: '4.8',
    reviews: '31',
    attractions: ['Tops Lookout', 'Temple of Leah (base)', 'Sirao Flower Garden', 'Sky Experience Adventure'],
    routes: [
      { from: 'Busay', to: 'Tops Lookout', time: '15 min' },
      { from: 'Busay', to: 'Cebu City Center', time: '20 min' },
    ],
    deliveryNote: 'Free delivery to Busay area in 35–55 minutes.',
    neighbors: ['cebu-city', 'banilad'],
  },
  {
    slug: 'minglanilla',
    name: 'Minglanilla',
    type: 'secondary',
    keyword: 'rent scooter minglanilla cebu',
    volume: 55,
    tagline: 'Free Delivery to Minglanilla',
    intro: 'Minglanilla is a quiet municipality south of Talisay. It\'s a great base for exploring south Cebu\'s waterfalls and beaches without the Cebu City traffic.',
    street: 'Minglanilla, Cebu',
    city: 'Minglanilla',
    postalCode: '6046',
    latitude: '10.2380',
    longitude: '123.7960',
    rating: '4.7',
    reviews: '19',
    attractions: ['Minglanilla Church', 'South Cebu Route', 'Talisay (15 min)', 'Naga (10 min)'],
    routes: [
      { from: 'Minglanilla', to: 'Talisay', time: '15 min' },
      { from: 'Minglanilla', to: 'Moalboal', time: '75 min' },
    ],
    deliveryNote: 'Free delivery to Minglanilla in 60–80 minutes.',
    neighbors: ['talisay'],
  },
  {
    slug: 'danao',
    name: 'Danao City',
    type: 'secondary',
    keyword: 'rent scooter danao cebu',
    volume: 50,
    tagline: 'Free Delivery to Danao City',
    intro: 'Danao City is a northern port city with ferry connections to Leyte and the Eastern Visayas. A scooter gives you the freedom to explore the less-visited north Cebu beaches.',
    street: 'Danao City, Cebu',
    city: 'Danao City',
    postalCode: '6004',
    latitude: '10.5212',
    longitude: '124.0265',
    rating: '4.7',
    reviews: '17',
    attractions: ['Danao Port (Leyte Ferry)', 'North Cebu Beaches', 'Liloan (20 min)', 'Compostella (10 min)'],
    routes: [
      { from: 'Danao', to: 'Liloan', time: '20 min' },
      { from: 'Danao', to: 'Cebu City', time: '60 min' },
    ],
    deliveryNote: 'Free delivery to Danao City in 70–90 minutes.',
    neighbors: ['liloan', 'compostella'],
  },
  {
    slug: 'compostella',
    name: 'Compostela',
    type: 'secondary',
    keyword: 'rent scooter compostela cebu',
    volume: 45,
    tagline: 'Free Delivery to Compostela',
    intro: 'Compostela is a scenic municipality on Cebu\'s northeast coast, known for its eco-tourism sites and unspoiled beaches. A scooter opens up the entire north Cebu coastline.',
    street: 'Compostela, Cebu',
    city: 'Compostela',
    postalCode: '6003',
    latitude: '10.4566',
    longitude: '124.0087',
    rating: '4.7',
    reviews: '14',
    attractions: ['Compostela Hills', 'Northeast Cebu Beaches', 'Danao City (10 min)', 'Liloan (20 min)'],
    routes: [
      { from: 'Compostela', to: 'Danao City', time: '10 min' },
      { from: 'Compostela', to: 'Cebu City', time: '65 min' },
    ],
    deliveryNote: 'Free delivery to Compostela in 75–95 minutes.',
    neighbors: ['danao', 'liloan'],
  },
];

export function getLocation(slug: string): LocationData | undefined {
  return LOCATIONS.find((l) => l.slug === slug);
}
