export interface Vehicle {
  brand: string;
  model: string;
  engine: string;
  daily: number;
  weekly: number;
  monthly: number;
  badge: string | null;
  slug: string;
  automatic: boolean;
  image: string;
  topSpeed: string;
  fuelTank: string;
  weight: string;
  description: string;
  features: string[];
  year: number;
}

export const vehicles: Vehicle[] = [
  {
    brand: 'Honda',
    model: 'Beat 110',
    engine: '110cc',
    daily: 499,
    weekly: 2500,
    monthly: 8500,
    badge: 'Best Value',
    slug: 'honda-beat-110',
    automatic: true,
    image: '/models/honda-beat-110.jpeg',
    topSpeed: '95 km/h',
    fuelTank: '3.7 L',
    weight: '92 kg',
    description: 'The lightest and most affordable scooter in our fleet. Perfect for navigating Cebu City traffic and exploring narrow streets. Fuel-efficient and easy to park anywhere.',
    features: ['Fuel injection (PGM-FI)', 'LED headlight', 'USB charging port', 'Under-seat storage', 'Side stand engine cut-off'],
    year: 2023,
  },
  {
    brand: 'Honda',
    model: 'Click V3 125',
    engine: '125cc',
    daily: 599,
    weekly: 3500,
    monthly: 10000,
    badge: 'Popular',
    slug: 'honda-click-125',
    automatic: true,
    image: '/models/honda-click-125.png',
    topSpeed: '115 km/h',
    fuelTank: '5.5 L',
    weight: '108 kg',
    description: 'Our most popular model. The Click V3 strikes the perfect balance between city agility and highway comfort. Ideal for day trips to Moalboal or Kawasan Falls.',
    features: ['Smart key system', 'Idling Stop System (ISS)', 'Honda Selectable Torque Control', 'LCD instrument panel', 'LED lights all-round'],
    year: 2024,
  },
  {
    brand: 'Mio',
    model: 'Gravis 125',
    engine: '125cc',
    daily: 600,
    weekly: 3500,
    monthly: 10000,
    badge: null,
    slug: 'mio-gravis-125',
    automatic: false,
    image: '/models/mio-gravis-125.png',
    topSpeed: '110 km/h',
    fuelTank: '5.0 L',
    weight: '104 kg',
    description: 'A sporty manual scooter for riders who prefer more engine control. The Mio Gravis delivers a dynamic ride with a modern design that stands out on Cebu roads.',
    features: ['Manual transmission', 'Blue Core engine technology', 'LED headlight', 'Digital instrument cluster', 'Sporty dual exhaust'],
    year: 2023,
  },
  {
    brand: 'Honda',
    model: 'Click 160',
    engine: '160cc',
    daily: 700,
    weekly: 4000,
    monthly: 12500,
    badge: null,
    slug: 'honda-click-160',
    automatic: true,
    image: '/models/honda-click-160.png',
    topSpeed: '130 km/h',
    fuelTank: '5.5 L',
    weight: '118 kg',
    description: 'More power for those who want to venture further. The Click 160 handles Cebu\'s highways with ease — great for trips to Oslob whale sharks or Bantayan Island ferry.',
    features: ['eSP+ engine technology', 'Honda Selectable Torque Control', 'Smart key', 'Full-LED lighting', 'Large under-seat compartment'],
    year: 2024,
  },
  {
    brand: 'Yamaha',
    model: 'Aerox V2 155',
    engine: '155cc',
    daily: 750,
    weekly: 4500,
    monthly: 13000,
    badge: 'Top Case',
    slug: 'yamaha-aerox-v2',
    automatic: true,
    image: '/models/yamaha-aerox-v2-155.webp',
    topSpeed: '140 km/h',
    fuelTank: '4.8 L',
    weight: '125 kg',
    description: 'Sport-styled and fast. The Aerox V2 turns heads on every street in Cebu. Comes with a top case for extra luggage — perfect for longer island explorations.',
    features: ['VVA (Variable Valve Actuation)', 'Traction Control System', 'Top case included', 'Full-LED with DRL', 'Y-Connect Bluetooth dashboard'],
    year: 2024,
  },
  {
    brand: 'Honda',
    model: 'PCX 160',
    engine: '160cc',
    daily: 800,
    weekly: 5000,
    monthly: 15000,
    badge: 'Top Case',
    slug: 'honda-pcx-160',
    automatic: true,
    image: '/models/honda-pcx-160.png',
    topSpeed: '130 km/h',
    fuelTank: '8.1 L',
    weight: '132 kg',
    description: 'Premium comfort for longer journeys. The PCX 160\'s large fuel tank means you can ride all day without stops. The most comfortable seat in our fleet. Includes top case.',
    features: ['Large 8.1L fuel tank', 'Smart key with answer-back', 'Top case included', 'USB-C charging port', 'Honda Selectable Torque Control'],
    year: 2024,
  },
  {
    brand: 'Yamaha',
    model: 'Nmax V3 155',
    engine: '155cc',
    daily: 850,
    weekly: 5000,
    monthly: 15000,
    badge: 'Premium',
    slug: 'yamaha-nmax-155',
    automatic: true,
    image: '/models/yamaha-nmax-155.avif',
    topSpeed: '130 km/h',
    fuelTank: '7.1 L',
    weight: '134 kg',
    description: 'The premium touring choice. Nmax V3 redefines comfort with its upright riding position, wide seat, and advanced tech. Ideal for multi-day tours around Cebu province.',
    features: ['VVA engine with TCS', 'Y-Connect Bluetooth app', 'Smart key system', 'ABS braking', 'Adjustable windscreen'],
    year: 2024,
  },
  {
    brand: 'Honda',
    model: 'ADV 160',
    engine: '160cc',
    daily: 900,
    weekly: 6000,
    monthly: 18000,
    badge: 'Adventure',
    slug: 'honda-adv-160',
    automatic: false,
    image: '/models/honda-adv-160.png',
    topSpeed: '120 km/h',
    fuelTank: '8.1 L',
    weight: '135 kg',
    description: 'Built for adventure. The ADV 160 tackles both Cebu\'s city streets and rough mountain roads to destinations like Osmeña Peak and Kawasan. Our most capable machine.',
    features: ['Long-travel suspension', 'Off-road capable tires', 'Large 8.1L tank', 'Knuckle guards', 'Skid plate protection'],
    year: 2024,
  },
];
